api:
  retries: 3
  timeout: 10
  rate_limit: 100

cache:
  ttl: 3600  # Cache TTL in seconds
  max_size: 1000  # Maximum number of items in cache

logging:
  level: INFO
  file: financial_analyzer.log
